name: Weekly Concert Alert

on:
  schedule:
    - cron: '0 9 * * 0' # Runs every Sunday at 09:00 UTC
  workflow_dispatch: # Allows manual runs

jobs:
  build-and-create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write # IMPORTANT: Gives the Action permission to create/close issues

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run concert checker and generate content
        id: concert_data
        env:
          BANDSINTOWN_APP_ID: ${{ secrets.BANDSINTOWN_APP_ID }}
        run: python concert_checker.py

      - name: Close previous concert alert issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh issue list --label "concert-alert" --state open --limit 5 --json number | jq '.[].number' | xargs -I {} gh issue close {}
          echo "Closed old issues."

      - name: Create new concert alert issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh issue create \
            --title "${{ steps.concert_data.outputs.issue_title }}" \
            --body "${{ steps.concert_data.outputs.issue_body }}" \
            --label "concert-alert" \
            --assignee "${{ secrets.ASSIGNEE_USERNAME }}" # <-- CORRECTED SECRET NAME
          echo "Created new issue."