name: Weekly Concert Alert

on:
  schedule:
    - cron: '0 9 * * 0'
  workflow_dispatch:

jobs:
  build-and-create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write       # Permission to create/close issues
      contents: read      # <-- ADD THIS LINE: Permission for actions/checkout to read the repository contents

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run concert checker and generate content
        id: concert_data
        env:
          TICKETMASTER_API_KEY: ${{ secrets.TICKETMASTER_API_KEY }}
        run: python concert_checker.py

      # --- NEW STEP: Commit the generated RSS file back to the repository ---
      - name: Commit RSS feed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated: Update concert RSS feed"
          commit_user_name: "GitHub Actions Bot"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          file_pattern: concerts.rss # Only commit this specific file if it changes

      - name: Close previous concert alert issues
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh issue list --label "concert-alert" --state open --limit 5 --json number | jq '.[].number' | xargs -I {} gh issue close {}
          echo "Closed old issues."

      - name: Create new concert alert issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          gh issue create \
            --title "${{ steps.concert_data.outputs.issue_title }}" \
            --body "${{ steps.concert_data.outputs.issue_body }}" \
            --label "concert-alert" \
            --assignee "${{ secrets.ASSIGNEE_USERNAME }}"
          echo "Created new issue."